from __future__ import annotations

import re
from pathlib import Path

from .c2pa_forensics import inspect_c2pa
from .evidence import build_evidence_scores, build_evidence_summary
from .extract import extract_text
from .models import AuditReport, C2PAReport
from .providers import get_detector
from .segments import analyse_segments
from .stylometry import analyse_stylometry
from .unicode_forensics import scan_unicode


WORD_RE = re.compile(r"\b[\w'-]+\b", re.UNICODE)


def audit_text(
    text: str,
    source: str = "inline",
    provider: str = "anthropic",
    *,
    include_segments: bool = True,
    c2pa_report: C2PAReport | None = None,
) -> AuditReport:
    verifier = get_detector(provider)
    verification = verifier.verify(text)
    unicode_report = scan_unicode(text)
    stylometry_report = analyse_stylometry(text)
    c2pa = c2pa_report or C2PAReport(
        status="not_applicable",
        manifest_present=None,
        validation_ok=None,
        reason="C2PA inspection applies to supported files, not raw pasted text.",
    )
    segments = analyse_segments(text) if include_segments and len(WORD_RE.findall(text)) >= 50 else []
    summary = build_evidence_summary(verification, c2pa, unicode_report, stylometry_report)
    scores = build_evidence_scores(verification, c2pa, unicode_report, stylometry_report)

    limitations = [
        "A provider watermark is not the same as generic AI-style detection.",
        "Short samples usually provide less signal than long passages.",
        "Absence of a detectable mark does not prove human authorship or absence of AI processing.",
        "Unicode and stylometric findings are observational and can have ordinary non-AI explanations.",
        "C2PA proves statements bound to an asset when validation succeeds; it does not by itself prove that every word was originally generated by the named software.",
    ]

    return AuditReport(
        source=source,
        chars=len(text),
        words=len(WORD_RE.findall(text)),
        watermark_verification=verification,
        unicode_forensics=unicode_report,
        stylometry=stylometry_report,
        c2pa=c2pa,
        segments=segments,
        evidence_summary=summary,
        evidence_scores=scores,
        limitations=limitations,
    )


def audit_file(
    path: str | Path,
    provider: str = "anthropic",
    *,
    include_segments: bool = True,
    inspect_file_provenance: bool = True,
) -> AuditReport:
    path = Path(path)
    try:
        text = extract_text(path)
    except ValueError:
        # Non-text C2PA assets can still be audited for signed provenance.
        text = ""
    c2pa = inspect_c2pa(path) if inspect_file_provenance else C2PAReport(
        status="not_checked",
        manifest_present=None,
        validation_ok=None,
        reason="C2PA inspection was disabled by the caller.",
    )
    resolved_provider = provider
    if provider == "auto":
        resolved_provider = next((p for p in c2pa.provider_hints if p in {"anthropic", "google"}), "none")
    return audit_text(
        text,
        source=str(path),
        provider=resolved_provider,
        include_segments=include_segments,
        c2pa_report=c2pa,
    )
